import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import LeftSidebar, { MobileNav } from "@/components/layout/left-bar";
import RightSidebar from "@/components/layout/right-bar";
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

export const metadata: Metadata = {
  title: "TalkRo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  model,
}: Readonly<{
  children: React.ReactNode;
  model: React.ReactNode;
}>) {


  return (

    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={plusJakartaSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="min-h-screen bg-background text-foreground selection:bg-sky-500/30 overflow-x-hidden">
            <div className="flex w-full mx-auto relative">
              <div className="hidden sm:block">
                <LeftSidebar />
              </div>
              <main className="flex-1 mx-auto flex flex-col relative min-h-screen max-w-full">
                {children}
                {model}
              </main>
            </div>
            <MobileNav />
          </div>

        </ThemeProvider>
      </body>
    </html>
  );
}
