import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import LeftSidebar, { MobileNav } from "@/components/layout/left-bar";
import RightSidebar from "@/components/layout/right-bar";
import FloatingChatRenderer from "@/components/message/ChatRender";




const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

export const metadata: Metadata = {
  title: "TalkRo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  model,
}: Readonly<{
  children: React.ReactNode;
  model: React.ReactNode;
}>) {


  return (

    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={plusJakartaSans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-full mx-auto flex justify-between grid-cols-[1fr_minmax(0,740px)_1fr] gap-6 min-h-screen">

            <div className="hidden sm:block">
              <LeftSidebar />
            </div>

            <main className="flex flex-col relative max-w-full min-w-full sm:max-w-[740px] lg:min-w-[740px]  md:min-w-[640px] min-h-screen">
              {children}
              {model}
            </main>

            <div className="hidden md:block">
              <RightSidebar />
            </div>

          </div>

         <FloatingChatRenderer />

          <MobileNav />


        </ThemeProvider>
      </body>
    </html>
  );
}
